apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 042786454503.dkr.ecr.us-east-1.amazonaws.com/application/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
